spring.application.name: consumer-service
server.port: 8091

eureka.client.register-with-eureka: true
eureka.client.fetch-registry: true
eureka.client.service-url.defaultZone: http://localhost:8080/eureka